### ISSUE TITLE
Feature request: ability to process include directives recursively

### ISSUE THREAD

**Issue by dudinea** [dudinea/yaml-include-transformer#4]
Add ability to process include directives recursively.

An example of such a use-case (from argocd-cm):

```yaml
# List of Lua Scripts to introduce custom actions
  resource.customizations.actions.apps_Deployment: |
    # Lua Script to indicate which custom actions are available on the resource
    discovery.lua: |
      actions = {}
      actions["restart"] = {}
      return actions
    definitions:
      - name: restart
        # Lua Script to modify the obj
        action.lua: |
          local os = require("os")
          ...
```

Sould be defined as something like:

argocd-cm:
```yaml
resource.customizations.actions.apps_Deployment!rtextfile: filename.yaml
```

filename.yaml:
```yaml
discovery.lua!textfile: discovery.lua
definitions:
  - name: restart
    action.lua!textfile:  restart_action.lua
```
